import { StatusSummary } from "../api/status";

export function buildBarChartConfig(data: unknown[]): unknown {
  return {
    type: "chart",
    title: "",
    showTitle: false,
    showDownloadMediaButton: false,
    theme: "theme-blue",
    animate: false,
    fontSize: "medium",
    lineDatapointStyle: "hover",
    barHasBorder: "false",
    isLollipopChart: false,
    lollipopShape: "circle",
    lollipopColorStyle: "two-tone",
    visualizationSubType: "regular",
    barStyle: "flat",
    roundingStyle: "standard",
    tipRounding: "top",
    general: {
      showDownloadButton: false,
    },
    padding: {
      left: 5,
      right: 5,
    },
    yAxis: {
      hideAxis: false,
      displayNumbersOnBar: false,
      hideLabel: false,
      hideTicks: false,
      size: "10",
      gridLines: false,
      enablePadding: false,
      min: "",
      max: "",
      labelColor: "#333",
      tickLabelColor: "#333",
      tickColor: "#333",
      rightHideAxis: true,
      rightAxisSize: 50,
      rightLabel: "",
      rightLabelOffsetSize: 0,
      rightAxisLabelColor: "#333",
      rightAxisTickLabelColor: "#333",
      rightAxisTickColor: "#333",
      numTicks: "",
      axisPadding: 0,
      tickRotation: 0,
      anchors: [],
      type: "chart",
      title: "",
      showTitle: true,
      showDownloadMediaButton: false,
      theme: "theme-blue",
      animate: false,
      fontSize: "medium",
      lineDatapointStyle: "hover",
      barHasBorder: "false",
      isLollipopChart: false,
      lollipopShape: "circle",
      lollipopColorStyle: "two-tone",
      visualizationSubType: "regular",
      barStyle: "",
      roundingStyle: "standard",
      tipRounding: "top",
      general: {
        showDownloadButton: false,
      },
      padding: {
        left: 5,
        right: 5,
      },
      yAxis: {
        hideAxis: false,
        displayNumbersOnBar: false,
        hideLabel: false,
        hideTicks: false,
        size: 50,
        gridLines: false,
        enablePadding: false,
        min: "",
        max: "",
        labelColor: "#333",
        tickLabelColor: "#333",
        tickColor: "#333",
        rightHideAxis: true,
        rightAxisSize: 0,
        rightLabel: "",
        rightLabelOffsetSize: 0,
        rightAxisLabelColor: "#333",
        rightAxisTickLabelColor: "#333",
        rightAxisTickColor: "#333",
        numTicks: "",
        axisPadding: 0,
        tickRotation: 0,
        anchors: [],
        dataKey: "count",
      },
      boxplot: {
        plots: [],
        borders: "true",
        firstQuartilePercentage: 25,
        thirdQuartilePercentage: 75,
        boxWidthPercentage: 40,
        plotOutlierValues: false,
        plotNonOutlierValues: true,
        legend: {
          showHowToReadText: false,
          howToReadText: "",
        },
        labels: {
          q1: "Lower Quartile",
          q2: "q2",
          q3: "Upper Quartile",
          q4: "q4",
          minimum: "Minimum",
          maximum: "Maximum",
          mean: "Mean",
          median: "Median",
          sd: "Standard Deviation",
          iqr: "Interquartile Range",
          total: "Total",
          outliers: "Outliers",
          values: "Values",
          lowerBounds: "Lower Bounds",
          upperBounds: "Upper Bounds",
        },
      },
      topAxis: {
        hasLine: false,
      },
      isLegendValue: false,
      barThickness: 0.35,
      barHeight: 25,
      barSpace: 15,
      heights: {
        vertical: 300,
        horizontal: 240,
      },
      xAxis: {
        anchors: [],
        type: "categorical",
        showTargetLabel: true,
        targetLabel: "Target",
        hideAxis: false,
        hideLabel: false,
        hideTicks: false,
        size: 75,
        tickRotation: 0,
        min: "",
        max: "",
        labelColor: "#333",
        tickLabelColor: "#333",
        tickColor: "#333",
        numTicks: "",
        labelOffset: 65,
        axisPadding: 0,
        target: 0,
        sortDates: false,
        maxTickRotation: 0,
        dataKey: "age_group",
      },
      table: {
        label: "Data Table",
        expanded: false,
        limitHeight: false,
        height: "",
        caption: "",
        showDownloadUrl: false,
        showDataTableLink: true,
        indexLabel: "",
        download: false,
        showVertical: true,
        show: false,
      },
      orientation: "horizontal",
      color: "pinkpurple",
      columns: {},
      legend: {
        behavior: "isolate",
        singleRow: false,
        colorCode: "",
        reverseLabelOrder: false,
        description: "",
        dynamicLegend: false,
        dynamicLegendDefaultText: "Show All",
        dynamicLegendItemLimit: 5,
        dynamicLegendItemLimitMessage: "Dynamic Legend Item Limit Hit.",
        dynamicLegendChartMessage: "Select Options from the Legend",
        lineMode: false,
        verticalSorted: false,
      },
      exclusions: {
        active: false,
        keys: [],
      },
      palette: "qualitative-bold",
      isPaletteReversed: false,
      twoColor: {
        palette: "monochrome-1",
        isPaletteReversed: false,
      },
      labels: false,
      dataFormat: {
        commas: false,
        prefix: "",
        suffix: "",
        abbreviated: false,
        bottomSuffix: "",
        bottomPrefix: "",
        bottomAbbreviated: false,
      },
      confidenceKeys: {},
      visual: {
        border: true,
        accent: true,
        background: true,
        verticalHoverLine: false,
        horizontalHoverLine: false,
      },
      useLogScale: false,
      filterBehavior: "Filter Change",
      highlightedBarValues: [],
      series: [
        {
          dataKey: "count",
          type: "Bar",
          axis: "Left",
          tooltip: true,
        },
      ],
      debugSvg: false,
      showChartBrush: false,
      isResponsiveTicks: false,
      tooltips: {
        opacity: 90,
      },
      brush: {
        pattern_id: "brush_pattern",
        accent_color: "#ddd",
      },
      visualizationType: "Bar",
      data,
      dataFileSourceType: "file",
      dataDescription: {
        horizontal: false,
        series: false,
      },
      validated: 4.23,
      runtime: {
        seriesLabels: {
          count: "count",
        },
        seriesLabelsAll: ["count"],
        originalXAxis: {
          anchors: [],
          type: "categorical",
          showTargetLabel: true,
          targetLabel: "Target",
          hideAxis: false,
          hideLabel: false,
          hideTicks: false,
          size: 75,
          tickRotation: 0,
          min: "",
          max: "",
          labelColor: "#333",
          tickLabelColor: "#333",
          tickColor: "#333",
          numTicks: "",
          labelOffset: 65,
          axisPadding: 0,
          target: 0,
          sortDates: false,
          maxTickRotation: 0,
          dataKey: "age_group",
        },
        seriesKeys: ["count"],
        xAxis: {
          hideAxis: false,
          displayNumbersOnBar: false,
          hideLabel: false,
          hideTicks: false,
          size: 50,
          gridLines: false,
          enablePadding: false,
          min: "",
          max: "",
          labelColor: "#333",
          tickLabelColor: "#333",
          tickColor: "#333",
          rightHideAxis: true,
          rightAxisSize: 0,
          rightLabel: "",
          rightLabelOffsetSize: 0,
          rightAxisLabelColor: "#333",
          rightAxisTickLabelColor: "#333",
          rightAxisTickColor: "#333",
          numTicks: "",
          axisPadding: 0,
          tickRotation: 0,
          anchors: [],
          dataKey: "count",
        },
        yAxis: {
          anchors: [],
          type: "categorical",
          showTargetLabel: true,
          targetLabel: "Target",
          hideAxis: false,
          hideLabel: false,
          hideTicks: false,
          size: 75,
          tickRotation: 0,
          min: "",
          max: "",
          labelColor: "#333",
          tickLabelColor: "#333",
          tickColor: "#333",
          numTicks: "",
          labelOffset: 65,
          axisPadding: 0,
          target: 0,
          sortDates: false,
          maxTickRotation: 0,
          dataKey: "age_group",
        },
        horizontal: true,
        uniqueId: 1702323188882,
        editorErrorMessage: "",
      },
      labelPlacement: "Below Bar",
    },
    boxplot: {
      plots: [],
      borders: "true",
      firstQuartilePercentage: 25,
      thirdQuartilePercentage: 75,
      boxWidthPercentage: 40,
      plotOutlierValues: false,
      plotNonOutlierValues: true,
      legend: {
        showHowToReadText: false,
        howToReadText: "",
      },
      labels: {
        q1: "Lower Quartile",
        q2: "q2",
        q3: "Upper Quartile",
        q4: "q4",
        minimum: "Minimum",
        maximum: "Maximum",
        mean: "Mean",
        median: "Median",
        sd: "Standard Deviation",
        iqr: "Interquartile Range",
        total: "Total",
        outliers: "Outliers",
        values: "Values",
        lowerBounds: "Lower Bounds",
        upperBounds: "Upper Bounds",
      },
    },
    topAxis: {
      hasLine: false,
    },
    isLegendValue: false,
    barThickness: 0.35,
    barHeight: 25,
    barSpace: 15,
    heights: {
      vertical: 300,
      horizontal: 369.59999999999997,
    },
    xAxis: {
      anchors: [],
      type: "categorical",
      showTargetLabel: true,
      targetLabel: "Target",
      hideAxis: false,
      hideLabel: false,
      hideTicks: false,
      size: 75,
      tickRotation: 0,
      min: "",
      max: "",
      labelColor: "#333",
      tickLabelColor: "#333",
      tickColor: "#333",
      numTicks: "",
      labelOffset: 65,
      axisPadding: 0,
      target: 0,
      sortDates: false,
      maxTickRotation: 0,
      dataKey: "age_group",
    },
    table: {
      label: "Data Table",
      expanded: true,
      limitHeight: false,
      height: "",
      caption: "",
      showDownloadUrl: false,
      showDataTableLink: true,
      indexLabel: "",
      download: false,
      showVertical: true,
      show: false,
    },
    orientation: "vertical",
    color: "pinkpurple",
    columns: {},
    legend: {
      behavior: "isolate",
      singleRow: false,
      colorCode: "",
      reverseLabelOrder: false,
      description: "",
      dynamicLegend: false,
      dynamicLegendDefaultText: "Show All",
      dynamicLegendItemLimit: 5,
      dynamicLegendItemLimitMessage: "Dynamic Legend Item Limit Hit.",
      dynamicLegendChartMessage: "Select Options from the Legend",
      lineMode: false,
      verticalSorted: false,
      hide: true,
    },
    exclusions: {
      active: false,
      keys: [],
    },
    palette: "qualitative-bold",
    isPaletteReversed: false,
    twoColor: {
      palette: "monochrome-1",
      isPaletteReversed: false,
    },
    labels: false,
    dataFormat: {
      commas: false,
      prefix: "",
      suffix: "",
      abbreviated: false,
      bottomSuffix: "",
      bottomPrefix: "",
      bottomAbbreviated: false,
    },
    confidenceKeys: {},
    visual: {
      border: true,
      accent: true,
      background: true,
      verticalHoverLine: false,
      horizontalHoverLine: false,
    },
    useLogScale: false,
    filterBehavior: "Filter Change",
    highlightedBarValues: [],
    series: [
      {
        dataKey: "count",
        type: "Bar",
        axis: "Left",
        tooltip: true,
      },
    ],
    debugSvg: false,
    showChartBrush: false,
    isResponsiveTicks: false,
    tooltips: {
      opacity: 90,
    },
    brush: {
      pattern_id: "brush_pattern",
      accent_color: "#ddd",
    },
    visualizationType: "Bar",
    data,
    dataFileSourceType: "file",
    dataDescription: {
      horizontal: false,
      series: false,
    },
    validated: 4.23,
  };
}

export function buildPieChartConfig(data: unknown[]): unknown {
  return {
    type: "chart",
    debugSvg: false,
    title: "",
    showTitle: true,
    showDownloadMediaButton: false,
    showChartBrush: false,
    theme: "theme-blue",
    animate: false,
    fontSize: "medium",
    lineDatapointStyle: "hover",
    barHasBorder: "false",
    isLollipopChart: false,
    lollipopShape: "circle",
    lollipopColorStyle: "two-tone",
    visualizationSubType: "regular",
    barStyle: "",
    roundingStyle: "standard",
    tipRounding: "top",
    isResponsiveTicks: false,
    general: {
      showDownloadButton: false,
    },
    padding: {
      left: 5,
      right: 5,
    },
    yAxis: {
      hideAxis: false,
      displayNumbersOnBar: false,
      hideLabel: false,
      hideTicks: false,
      size: 50,
      gridLines: false,
      enablePadding: false,
      min: "",
      max: "",
      labelColor: "#333",
      tickLabelColor: "#333",
      tickColor: "#333",
      rightHideAxis: true,
      rightAxisSize: 0,
      rightLabel: "",
      rightLabelOffsetSize: 0,
      rightAxisLabelColor: "#333",
      rightAxisTickLabelColor: "#333",
      rightAxisTickColor: "#333",
      numTicks: "",
      axisPadding: 0,
      tickRotation: 0,
      anchors: [],
      dataKey: "count",
    },
    topAxis: {
      hasLine: false,
    },
    isLegendValue: false,
    barThickness: 0.35,
    barHeight: 25,
    barSpace: 15,
    heights: {
      vertical: 300,
      horizontal: 750,
    },
    xAxis: {
      sortDates: false,
      anchors: [],
      type: "categorical",
      showTargetLabel: true,
      targetLabel: "Target",
      hideAxis: false,
      hideLabel: false,
      hideTicks: false,
      size: 75,
      tickRotation: 0,
      min: "",
      max: "",
      labelColor: "#333",
      tickLabelColor: "#333",
      tickColor: "#333",
      numTicks: "",
      labelOffset: 65,
      axisPadding: 0,
      target: 0,
      maxTickRotation: 0,
      dataKey: "age_group",
    },
    table: {
      label: "Data Table",
      expanded: true,
      limitHeight: false,
      height: "",
      caption: "",
      showDownloadUrl: false,
      showDataTableLink: true,
      indexLabel: "",
      download: false,
      showVertical: true,
      show: false,
    },
    orientation: "vertical",
    color: "pinkpurple",
    columns: {},
    legend: {
      behavior: "isolate",
      singleRow: false,
      colorCode: "",
      reverseLabelOrder: false,
      description: "",
      dynamicLegend: false,
      dynamicLegendDefaultText: "Show All",
      dynamicLegendItemLimit: 5,
      dynamicLegendItemLimitMessage: "Dynamic Legend Item Limit Hit.",
      dynamicLegendChartMessage: "Select Options from the Legend",
      lineMode: false,
      verticalSorted: false,
    },
    exclusions: {
      active: false,
      keys: [],
    },
    palette: "qualitative-bold",
    isPaletteReversed: false,
    twoColor: {
      palette: "monochrome-1",
      isPaletteReversed: false,
    },
    labels: false,
    dataFormat: {
      commas: false,
      prefix: "",
      suffix: "",
      abbreviated: false,
      bottomSuffix: "",
      bottomPrefix: "",
      bottomAbbreviated: false,
    },
    confidenceKeys: {},
    visual: {
      border: true,
      accent: true,
      background: true,
      verticalHoverLine: false,
      horizontalHoverLine: false,
    },
    useLogScale: false,
    filterBehavior: "Filter Change",
    highlightedBarValues: [],
    series: [],
    tooltips: {
      opacity: 90,
    },
    brush: {
      pattern_id: "brush_pattern",
      accent_color: "#ddd",
    },
    visualizationType: "Pie",
    data,
    dataFileSourceType: "file",
    dataDescription: {
      horizontal: false,
      series: false,
    },
    validated: 4.23,
  };
}

export function transformStatus(data: StatusSummary): unknown[] {
  const transformedArray = [] as unknown[];
  const dataKeys = Object.keys(data).filter((_, index) => index !== 0);

  dataKeys.forEach((key) => {
    transformedArray.push({
      label: key,
      count: data[key as keyof typeof data],
    });
  });

  return transformedArray;
}
